apis_acdhch_default_settings/settings.py
its a variable of the `webpage` module which is not a dependency
anymore. also, the default should be used.
=> fix: drop ACDH_IMPRINT_URL

apis_acdhch_default_settings/settings.py
apis-rdf-core in version 0.3.0 now updated the settings for the default
list view template. The `browsing/generic_list.html` template was
removed and the new value does not need to be overridden anymore.
=> fix: remove the list view template override

apis_acdhch_default_settings/settings.py
apis-core-rdf v0.5 uses the apiscore templatetag which resides in the
`apis_core.core` app - so we have to add this one to the list of
INSTALLED_APPS.
=> fix: add apis_core.core to installed apps

apis_acdhch_default_settings/settings.py
Starting from v0.6 APIS does not contain charts code anymore, so we can
drop it.
=> fix: drop charts dependency

pyproject.toml
apis-override-select2js is a dependency of apis-core, not from the
default settings
=> fix: drop apis-override-select2js from dependencies

apis_acdhch_default_settings/settings.py
`PUBLIC_URL` is now passed through to the container, so we can use it to
add the hostname to `ALLOWED_HOSTS`
Closes: #28
=> fix: get `ALLOWED_HOSTS` from `PUBLIC_URL`

.github/workflows/release-please.yml
gh says: To use GitHub CLI in a GitHub Actions workflow, set the
GH_TOKEN environment variable
=> ci: add GH_TOKEN to ci workflow

apis_acdhch_default_settings/settings.py
we don't use that anymore, we use CSP instead
=> fix: drop django-cors-headers related settings

apis_acdhch_default_settings/settings.py
This will be used starting from apis-core-rdf v0.9.0
=> fix: add crispy_bootstrap4 to list of installed apps

apis_acdhch_default_settings/settings.py
`apis_ontology` is an app, therefore it is already looking for templates
in its templates folder
=> fix: TEMPLATES: remove apis_ontology/templates from DIRS

apis_acdhch_default_settings/settings.py
=> fix: use random secret key instead of hardcoding it

apis_acdhch_default_settings/settings.py
we don't use guardian anymore, therefore there are not object
permissions
=> fix: set drf DEFAULT_PERMISSION_CLASSES to model permission

apis_acdhch_default_settings/settings.py
Include new app introduced in apis-core-rdf v0.10.0 release
=> fix: add 'generic' app to INSTALLED_APPS

apis_acdhch_default_settings/settings.py
APIS ships a default generator class since v0.16.0, lets use it in
our default setups.
Closes: #84
=> fix(spectacular): set DEFAULT_GENERATOR_CLASS

apis_acdhch_default_settings/settings.py
This way we can override templates
=> fix: put apis_ontology before apis_core in INSTALLED_APPS

apis_acdhch_default_settings/templates/base.html
The imprint url should not point to django_acdhch_functions, this was a
leftover from importing the code from django_acdhch_functions. This was
replaced with the correct route and an `as` syntax, which does not raise
a NoReverseMatch exception.
=> fix(template): make imprint url handling more robust

apis_acdhch_default_settings/urls.py
The webpape app is not used anymore in APIS and thus it makes sense to
remove it from the routing configuration.
Closes: #114
=> fix(urls): drop inclusion of webpage app in urls

apis_acdhch_default_settings/settings.py
This commit introduces a check for the DJANGO_DEBUG environment
variable, which allows us to set the DEBUG setting of Django.
=> feat(settings): allow to set DEBUG from environment

apis_acdhch_default_settings/settings.py
=> feat(settings): point LOGIN_URL to the default APIS login route

apis_acdhch_default_settings/settings.py
`apis_relations` will be dropped from the next apis-core-rdf release, so
it makes sense to remove it from the default settings now.
=> feat(settings)!: drop apis_relations from INSTALLED_APPS

.github/workflows/add-to-project.yml
Add `pull_request` trigger to `add-to-project`
workflow so both (new/opened) issues and PRs
are added to the Prosnet project.
Update workflow `name` to reflect this change.
Closes: #162
=> ci: run add-to-project workflow also on PRs

apis_acdhch_default_settings/settings.py
This also incldues `data:` which is used by Bootstrap 5
=> feat(settings): introduce a separate CSP setting for images

apis_acdhch_default_settings/settings.py
(it's not a dependency of apis-core anymore)
=> fix(settings): drop apis_override_select2js from INSTALLED_APPS

pyproject.toml
Add `[project.urls]` setting to `pyproject.toml` in an attempt to make Dependabot generate clickable links to the project repository in its pull requests.
This should also generate clickable "Project links" on the project's package page on PyPI.
---
I just noticed (again) that the link to the repo is missing from Dependabot's prompts to update the dependency, so decided to fix this based on an internal discussion which was had a while ago.
=> build: add urls to project metadata

apis_acdhch_default_settings/settings.py
Add `CSP_FRAME_ANCESTORS` variable with web address to ÖAW-hosted GitLab pages to allow embedding of
APIS apps contents in GitLab-hosted presentations (iframes).
---
Follow-up to https://github.com/acdh-oeaw/apis-acdhch-default-settings/pull/138#issuecomment-2621510940.
This setting [was added to TBF](https://github.com/acdh-oeaw/apis-instance-tbf/blob/16eb9b828a3eea14b4b8fafd01846945289bff3b/apis_ontology/settings.py#L16-L18) and seems to be working from what I can tell Though I'm not sure if the presentation which recently embedded part of the app would need to be redeployed. Not linking it here because it wasn't given publicly, but @sennierer knows where it's at.
=> feat(settings): (re)add Content Security Policy setting

pyproject.toml
Move main project metadata from `[tool.poetry]` section to new `[project]` section and update the format of individual settings which require it (like `authors`, `license`).
This change attempts to rectify the breaking of the config file's formatting when `[project.urls]` was introduced without an overall `[project]` section.
Not yet included is a conversion of the project dependencies to the Python/PyPA default format; for the moment, they are included dynamically.
Resolves: #175
=> build: move, convert project/package settings

apis_acdhch_default_settings/settings.py
Leaflet uses tiles from openstreetmap.org and icons from
cdnjs.cloudflare.com, so we need to allow those via CSP.
=> fix(settings): add resources used by leaflet to CSP_IMG_SRC

pyproject.toml
th poetry dependency list used the caret character to limit some of the
dependencies. we mimic this constraint using an upper limit.
=> build: readd version constraints lost on migration from poetry to uv

pyproject.toml
now that we use `uv` that should be safe
=> build: readd project urls

apis_acdhch_default_settings/templates/base.html
We should use this meta tag for monitoring instead of the `Title
Placeholder` string.
=> feat(templates): add a monitoring variable to the meta tags

apis_acdhch_default_settings/settings.py
The setting key contains a typo and has therefore never been used, but
we actually don't need it anyway.
=> refactor(settings): drop unused spectacular settings

apis_acdhch_default_settings/settings.py, pyproject.toml
Add `apis_core.uris` following `apis-core-rdf` release `v0.52.0`, which moved the `Uri` model to a separate app.
Closes: #247
=> feat(settings): add uris to INSTALLED_APPS
