acdh-oeaw/apis-acdhch-default-settings

pyproject.toml
=> fix(deps): add whitenoise dependency

apis_acdhch_default_settings/settings.py
changes imprint service to https://redmine.acdh.oeaw.ac.at/issues/21966
=> fix: updates base settings to new imprint service

apis_acdhch_default_settings/settings.py
=> fix: include ALLOWED_CIDR_NETS into settings

apis_acdhch_default_settings/settings.py
=> fix: provide default database setup

README.md, pyproject.toml
=> fix: add initial README

apis_acdhch_default_settings/settings.py
=> fix: drop deprecated context_processors

apis_acdhch_default_settings/settings.py
* removed settings that start with `APIS_` but where nowhere to be found
in the apis-core source
* removed AUTHENTICATION_BACKENDS, as it repeated the default setting
* merged two INSTALLED_APPS statements
* two small style refactorings
=> chore(settings): small cleanup

apis_acdhch_default_settings/settings.py
=> fix!: drop reversion

apis_acdhch_default_settings/settings.py
=> fix(settings): drop unused settings

apis_acdhch_default_settings/settings.py
Ref: https://docs.djangoproject.com/en/5.0/ref/clickjacking/
Closes: #47
=> fix(middlware): add middleware to prevent clickjacking

apis_acdhch_default_settings/settings.py
This configures the Django logging system to log all loglevels to stdout
=> feat(settings): introduce logging configuration

apis_acdhch_default_settings/settings.py
=> feat(settings): reuse PUBLIC_URL for APIS_BASE_URI

apis_acdhch_default_settings/urls.py
=> feat(urls): include staticfiles_urlpatterns in default urls

apis_acdhch_default_settings/settings.py
=> fix(settings): add HistoryRequestMiddleware

apis_acdhch_default_settings/settings.py, pyproject.toml
=> feat(deps): add django-removals dependency and add it to installed apps

apis_acdhch_default_settings/settings.py
=> fix: remove unused third party sources from CSP settings

apis_acdhch_default_settings/settings.py
=> fix(settings): drop deprecated USE_L10N setting

apis_acdhch_default_settings/settings.py
=> fix(settings): set default tables2 template to bootstrap5-reponsive

apis_acdhch_default_settings/settings.py
=> feat(settings): add collections, history to INSTALLED_APPS

apis_acdhch_default_settings/urls.py
This is a more robust way than to use settings.INSTALLED_APPS
See https://stackoverflow.com/a/43189917
Closes: #233
=> fix(urls): use apps.is_installed for checking app availability
